# NUMPY

In [5]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
a.shape

(3,)

In [7]:
a.dtype

dtype('int32')

In [8]:
a.size

3

In [9]:
a.itemsize

4

In [10]:
a.nbytes

12

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
b.shape

(2, 7)

In [13]:
b[1,0]

8

In [14]:
b[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
b[:,2]

array([ 3, 10])

In [16]:
b[1,5]=20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
b[:, 2]=[1,5]
print(b)

[[ 1  2  1  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
np.full((2,2), 33)

array([[33, 33],
       [33, 33]])

In [22]:
np.full_like(b, 4) # b'nin şekline göre

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
np.random.rand(4, 2) #Random decimal numbers

array([[0.23669897, 0.36937901],
       [0.65026017, 0.27452405],
       [0.97127455, 0.37768893],
       [0.50589194, 0.65314852]])

In [24]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###### Problem 1

In [25]:
x = np.full((5,5), 1)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [27]:
x[1:4, 1:4] = z
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Mathematics

In [28]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [29]:
a+5

array([6, 7, 8, 9])

In [30]:
a-2

array([-1,  0,  1,  2])

In [31]:
a*3

array([ 3,  6,  9, 12])

In [32]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [33]:
a=np.ones((2,3))
print(a)

b=np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [34]:
c=np.matmul(a,b)
print(c)

[[6. 6.]
 [6. 6.]]


In [35]:
np.linalg.det(c) #Determinant

0.0

#### Statistics

In [36]:
stats = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
stats

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [37]:
np.min(stats)

1

In [38]:
np.min(stats, axis=1) # Axis 0 ise satır, 1 ise sütun

array([1, 8])

In [39]:
np.max(stats)

14

In [40]:
np.max(stats, axis=0) 

array([ 8,  9, 10, 11, 12, 13, 14])

In [41]:
np.sum(stats)

105

In [43]:
np.sum(stats, axis=1)

array([28, 77])

In [44]:
np.sum(stats, axis=0)

array([ 9, 11, 13, 15, 17, 19, 21])

#### Reorganizing Arrays

In [49]:
before = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(before, before.shape)

after = before.reshape((7,2))
print(after)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [50]:
# Vertically stacking vectors (üst üste)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

x = np.vstack([v1,v2,v1,v2])
print(x)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [53]:
# Horizontal  stack (yan yana)
h1 = np.ones((2,4))
h2 = np.zeros((2,3))

y = np.hstack((h1,h2))
print(y)

[[1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]]


#### Load Data from File

In [57]:
filedata = np.genfromtxt('data.txt', delimiter=',')

filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [56]:
filedata = filedata.astype('int32') # Verilerin tipi değişti.
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [63]:
(((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [64]:
(~((filedata > 50) & (filedata < 100))) # Yukarıdakinin tersi

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [59]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [62]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

#### Problem 2

In [65]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a3 = np.array([11,12,13,14,15])
a4 = np.array([16,17,18,19,20])
a5 = np.array([21,22,23,24,25])
a6 = np.array([26,27,28,29,30])

t = np.vstack([a1,a2,a3,a4,a5,a6])
print(t)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [66]:
t[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [69]:
t[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [70]:
t[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])